export default {
    extends: ['stylelint-config-standard', 'stylelint-config-css-modules'],
    plugins: ['stylelint-order', 'stylelint-scss'],
    defaultSeverity: 'error',
    rules: {
        'media-feature-range-notation': 'prefix',
        'scss/at-mixin-argumentless-call-parentheses': 'never',
        'custom-property-empty-line-before': null,
        'custom-media-pattern': null,
        'custom-property-pattern': null,
        'no-duplicate-selectors': null,
        'no-descending-specificity': null,
        'property-no-vendor-prefix': null,
        'import-notation': 'string',
        'color-hex-length': null,
        'no-invalid-position-at-import-rule': null,
        'color-function-notation': null,
        'declaration-block-no-redundant-longhand-properties': null,
        'declaration-property-value-no-unknown': null,
        'declaration-empty-line-before': null,
        'order/properties-order': [
            [
                {
                    groupName: 'positioning',
                    properties: [
                        'position',
                        'inset',
                        'top',
                        'right',
                        'bottom',
                        'left',
                        'z-index',
                        'float',
                        'clear',
                    ],
                },
                {
                    groupName: 'display',
                    properties: [
                        'display',
                        'flex',
                        'flex-direction',
                        'flex-wrap',
                        'flex-flow',
                        'flex-grow',
                        'flex-shrink',
                        'flex-basis',
                        'align-items',
                        'align-content',
                        'align-self',
                        'justify-content',
                        'justify-items',
                        'justify-self',
                        'gap',
                        'row-gap',
                        'column-gap',
                        'order',
                        'grid',
                        'grid-template',
                        'grid-template-rows',
                        'grid-template-columns',
                        'grid-template-areas',
                        'grid-row',
                        'grid-column',
                        'grid-area',
                        'grid-auto-rows',
                        'grid-auto-columns',
                        'grid-auto-flow',
                    ],
                },
                {
                    groupName: 'box-model',
                    properties: [
                        'box-sizing',
                        'width',
                        'min-width',
                        'max-width',
                        'height',
                        'min-height',
                        'max-height',
                        'margin',
                        'margin-top',
                        'margin-right',
                        'margin-bottom',
                        'margin-left',
                        'padding',
                        'padding-top',
                        'padding-right',
                        'padding-bottom',
                        'padding-left',
                        'overflow',
                        'overflow-x',
                        'overflow-y',
                    ],
                },
                {
                    groupName: 'visual',
                    properties: [
                        'background',
                        'background-color',
                        'background-image',
                        'background-repeat',
                        'background-position',
                        'background-size',
                        'border',
                        'border-width',
                        'border-style',
                        'border-color',
                        'border-top',
                        'border-right',
                        'border-bottom',
                        'border-left',
                        'border-radius',
                        'outline',
                        'box-shadow',
                        'opacity',
                        'visibility',
                        'cursor',
                        'pointer-events',
                        'resize',
                    ],
                },
                {
                    groupName: 'typography',
                    properties: [
                        'font',
                        'font-family',
                        'font-size',
                        'font-weight',
                        'font-style',
                        'font-variant',
                        'line-height',
                        'letter-spacing',
                        'word-spacing',
                        'text-align',
                        'text-transform',
                        'text-decoration',
                        'text-overflow',
                        'text-shadow',
                        'color',
                        'white-space',
                        'word-break',
                        'overflow-wrap',
                    ],
                },
                {
                    groupName: 'animation',
                    properties: [
                        'transition',
                        'animation',
                        'transform',
                        'transform-origin',
                        'will-change',
                    ],
                },
            ],
            {
                severity: 'warning',
                unspecified: 'bottom',
            },
        ],
        'order/order': [
            [
                { type: 'at-rule', name: 'import' },
                { type: 'at-rule', name: 'forward' },
                { type: 'at-rule', name: 'use' },
                'dollar-variables',
                'at-variables',
                'custom-properties',
                { type: 'at-rule', name: 'custom-media' },
                { type: 'at-rule', name: 'function' },
                { type: 'at-rule', name: 'mixin' },
                { type: 'at-rule', name: 'extend' },
                { type: 'at-rule', name: 'include', hasBlock: true },
                'declarations',
                {
                    type: 'rule',
                    selector: /^&::[\w-]+/,
                    hasBlock: true,
                },
                'rules',
                { type: 'at-rule', name: 'media', hasBlock: true },
                { type: 'at-rule', name: 'include', hasBlock: true },
            ],
            {
                severity: 'warning',
            },
        ],
        'selector-class-pattern': [
            '^[A-Za-z]*(?:__[a-z]+(?:-[a-z]+)*)?(?:--[a-z]+(?:-[a-z]+)*)?$',
            {
                message: (selector: string) =>
                    `Expected class selector "${selector}" to be camelCase`,
            },
        ],
    },
};
